name: ksy90604
author: Herring Cove
baseurl: ""
url : "ksy90604.github.io"
description: theme for jekyll
github: ksy90604.github.io
email: ksy90604@gmail.com


##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
