name: ksy90604
author: ksy90604
baseurl: ""
url : "ksy90604.github.io"
description: Notes
github: "https://github.com/ksy90604"
email: "ksy90604@gmail.com"


##Make sure to edit the above fields, especially for disqus.
disqus_url : http://disqus.com/by/syKim64
disqus_id : syKim64

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
